#!/usr/bin/env python
# -*- coding: utf-8 -*-

from Segmenter import Segmenter
import sys

def main():
    model = sys.argv[1]

    s = Segmenter()
    s.learner.load(open(model))
    for line in iter(sys.stdin.readline, ""):
        line = line.strip()
        line = line.decode('utf-8')
        print ' '.join(s.parse(line))

if __name__=='__main__':
    main()
