#!/usr/bin/env python
# -*- coding: utf-8 -*-

from Segmenter import Segmenter
import sys

def main():
    in_file = sys.stdin
    out_file = sys.stdout

    s= Segmenter()
    for line in in_file:
        line = line.strip()
        line = line.decode('utf-8')
        s.addSentence(line)
    s.learner.train()
    s.learner.save(out_file)

if __name__=='__main__':
    main()
