#!/usr/bin/env python
# -*- coding: utf-8 -*-

from AdaBoost import AdaBoost
from Segmenter import addSentence
import sys

def main():
    in_file = sys.stdin
    out_file = sys.stdout

    learner = AdaBoost()
    for line in in_file:
        line = line.strip()
        line = line.decode('utf-8')
        addSentence(learner, line)
    learner.train()
    learner.save(out_file)

if __name__=='__main__':
    main()
